// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBBVd6aUVFv2oKT0BPM-BX0iMWnqdU8clw',
    appId: '1:685386374848:web:50b9d268ccfa17e967d725',
    messagingSenderId: '685386374848',
    projectId: 'mynotes-flutter-project1125',
    authDomain: 'mynotes-flutter-project1125.firebaseapp.com',
    storageBucket: 'mynotes-flutter-project1125.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCumNZYhOm2aDUOs0E8jisbKaci1gkao34',
    appId: '1:685386374848:android:32d05b35f88a711567d725',
    messagingSenderId: '685386374848',
    projectId: 'mynotes-flutter-project1125',
    storageBucket: 'mynotes-flutter-project1125.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBgKsj1cLgWlV1_PQrXgykpqqJdebxkcWc',
    appId: '1:685386374848:ios:636342b54918e03a67d725',
    messagingSenderId: '685386374848',
    projectId: 'mynotes-flutter-project1125',
    storageBucket: 'mynotes-flutter-project1125.appspot.com',
    iosBundleId: 'com.example.mynotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBgKsj1cLgWlV1_PQrXgykpqqJdebxkcWc',
    appId: '1:685386374848:ios:1397d66bbdbad33867d725',
    messagingSenderId: '685386374848',
    projectId: 'mynotes-flutter-project1125',
    storageBucket: 'mynotes-flutter-project1125.appspot.com',
    iosBundleId: 'com.example.mynotes.RunnerTests',
  );
}
